INFO - 2024-05-08 13:33:55 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 13:36:15 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 13:36:16 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 13:37:29 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 13:38:03 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 13:45:21 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
ERROR - 2024-05-08 13:54:35 --> Error connecting to the database: ErrorException: mysqli::real_connect(): Error while reading greeting packet. PID=16480 in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mysqli::real_co...', 'D:\\cahya2\\pemwe...', 184)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#6 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#7 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#8 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#14 {main}

Next mysqli_sql_exception: MySQL server has gone away in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: MySQL server has gone away in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:54:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: MySQL server has gone away
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:54:39 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:54:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:54:43 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:54:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:54:48 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:54:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:54:52 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:54:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:54:56 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:54:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:00 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:05 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:09 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:13 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:17 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:22 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:22 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:26 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:30 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:30 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:34 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:34 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:39 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
ERROR - 2024-05-08 13:55:43 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 13:55:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-08 13:56:59 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 202.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-08 14:00:10 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 202.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-08 14:02:25 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 202.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-08 14:09:29 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 202.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
ERROR - 2024-05-08 14:26:04 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#7 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#10 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#12 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 D:\cahya2\pemweb\pertemuan-4\app\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
#6 D:\cahya2\pemweb\pertemuan-4\app\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
#7 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(941): App\Controllers\Books->index()
#8 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
#9 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\cahya2\pemweb\pertemuan-4\public\index.php(79): CodeIgniter\CodeIgniter->run()
#11 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemwe...')
#12 {main}
CRITICAL - 2024-05-08 14:26:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `books`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Models\BooksModel.php(16): CodeIgniter\BaseModel->findAll()
 6 APPPATH\Controllers\Books.php(19): App\Models\BooksModel->getBooks()
 7 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Books->index()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Books))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('D:\\cahya2\\pemweb\\pertemuan-4\\public\\index.php')
CRITICAL - 2024-05-08 14:30:09 --> ErrorException: Maximum execution time of 60 seconds exceeded
in SYSTEMPATH\Debug\Exceptions.php on line 202.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-08 17:19:42 --> Error: Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 218.
 1 ROOTPATH\spark(88): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-05-08 17:19:42 --> ErrorException: Uncaught Error: Class "Locale" not found in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\I18n\TimeTrait.php:74
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\I18n\TimeTrait.php(115): CodeIgniter\I18n\Time->__construct(NULL, NULL, NULL)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(468): CodeIgniter\I18n\Time::now()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(446): CodeIgniter\HTTP\Response->sendHeaders()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Debug\ExceptionHandler.php(81): CodeIgniter\HTTP\Response->send()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Debug\Exceptions.php(156): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#6 {main}
  thrown
【Previous Exception】
Error
Class "Locale" not found
#0 D:\cahya2\pemweb\pertemuan-4\spark(88): CodeIgniter\CodeIgniter->initialize()
#1 {main}
in SYSTEMPATH\I18n\TimeTrait.php on line 74.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2024-05-08 17:22:17 --> Error: Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 218.
 1 ROOTPATH\spark(88): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2024-05-08 17:22:17 --> ErrorException: Uncaught Error: Class "Locale" not found in D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\I18n\TimeTrait.php:74
Stack trace:
#0 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\I18n\TimeTrait.php(115): CodeIgniter\I18n\Time->__construct(NULL, NULL, NULL)
#1 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(468): CodeIgniter\I18n\Time::now()
#2 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\HTTP\ResponseTrait.php(446): CodeIgniter\HTTP\Response->sendHeaders()
#3 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Debug\ExceptionHandler.php(81): CodeIgniter\HTTP\Response->send()
#4 D:\cahya2\pemweb\pertemuan-4\vendor\codeigniter4\framework\system\Debug\Exceptions.php(156): CodeIgniter\Debug\ExceptionHandler->handle(Object(Error), Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), 500, 1)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(Error))
#6 {main}
  thrown
【Previous Exception】
Error
Class "Locale" not found
#0 D:\cahya2\pemweb\pertemuan-4\spark(88): CodeIgniter\CodeIgniter->initialize()
#1 {main}
in SYSTEMPATH\I18n\TimeTrait.php on line 74.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
INFO - 2024-05-08 15:26:51 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 15:28:30 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 15:29:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 15:29:06 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 15:48:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 15:54:31 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 15:54:32 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
INFO - 2024-05-08 16:01:38 --> Session: Class initialized using 'CodeIgniter\Session\Handlers\FileHandler' driver.
